title: Soma Saito
description: Notes on mathematics, type theory, and formalized metatheory by Soma Saito.
url: "https://uch4sq.github.io"
baseurl: "/archive"
author: Soma Saito
lang: en
markdown: kramdown
permalink: pretty
exclude:
  - tmp
  - "**/*.tex"
